### ISSUE TITLE
Replace own github action gradle caching with built-in of setup-java

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#774]
In 
https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle
the github actions team does describe the internal caching for setup-java action:

> When using GitHub-hosted runners, you can cache your dependencies to speed up your workflow runs. After a successful run, your local Gradle package cache will be stored on GitHub Actions infrastructure. In future workflow runs, the cache will be restored so that dependencies don't need to be downloaded from remote package repositories. You can cache dependencies simply using the setup-java action or can use cache action for custom and more advanced configuration. 

so we can remove the manual caching steps and use integrated one.

The snippet for setup is:
```yaml
- name: Set up JDK 11
    uses: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'adopt'
      cache: gradle
``` 

For gradle wrapper validation there would be additional steps necessary - for details look at the mentioned link.

But this will not be handled inside this issue.
